/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Logins;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class Addcashiers extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Addcashiers
     */
    public Addcashiers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adduspw = new javax.swing.JTextField();
        addusname = new javax.swing.JTextField();
        addcashback = new javax.swing.JButton();
        addcashierm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Quicksand SemiBold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Toy Mart");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 130, 40));

        jLabel2.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Add Cashiers");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 90, 40));

        jLabel3.setFont(new java.awt.Font("Quicksand SemiBold", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Set a Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Quicksand SemiBold", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Cashier Username: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        adduspw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduspwActionPerformed(evt);
            }
        });
        jPanel1.add(adduspw, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 160, -1));

        addusname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addusnameActionPerformed(evt);
            }
        });
        jPanel1.add(addusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 160, -1));

        addcashback.setBackground(new java.awt.Color(255, 204, 204));
        addcashback.setFont(new java.awt.Font("Quicksand SemiBold", 1, 14)); // NOI18N
        addcashback.setForeground(new java.awt.Color(0, 0, 0));
        addcashback.setText("Back");
        addcashback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcashbackActionPerformed(evt);
            }
        });
        jPanel1.add(addcashback, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 150, -1));

        addcashierm.setBackground(new java.awt.Color(204, 255, 204));
        addcashierm.setFont(new java.awt.Font("Quicksand SemiBold", 1, 14)); // NOI18N
        addcashierm.setForeground(new java.awt.Color(0, 0, 0));
        addcashierm.setText("Add Cashier");
        addcashierm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcashiermActionPerformed(evt);
            }
        });
        jPanel1.add(addcashierm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adduspwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduspwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adduspwActionPerformed

    private void addusnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addusnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addusnameActionPerformed

    private void addcashbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcashbackActionPerformed
        Login_manager cm1 = new Login_manager();
        cm1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addcashbackActionPerformed

    private void addcashiermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcashiermActionPerformed
        try {
            String query = "INSERT INTO `systemlog`(`username`,`usertype`,`password`) VALUES (?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/lankesh", "root", "Wikum@123");
            pst = con.prepareStatement(query);
            pst.setString(1, addusname.getText());
            pst.setString(2, "Cashier");
            pst.setString(3, adduspw.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "New Cashier Added Successfully");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_addcashiermActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addcashiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addcashiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addcashiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addcashiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addcashiers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcashback;
    private javax.swing.JButton addcashierm;
    private javax.swing.JTextField addusname;
    private javax.swing.JTextField adduspw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
