/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Logins;

import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Cashier_func_manager extends javax.swing.JFrame {

    /**
     * Creates new form Cashier_func_manager
     */
    public Cashier_func_manager() {
        initComponents();
    }

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        toyamount = new javax.swing.JTextField();
        toyid = new javax.swing.JTextField();
        toyprice = new javax.swing.JTextField();
        toyqty = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        toyname = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        toybalance = new javax.swing.JTextField();
        finaltotal = new javax.swing.JTextField();
        toypayment = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bill = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(763, 470));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setFont(new java.awt.Font("Quicksand SemiBold", 1, 13)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(763, 459));
        jPanel1.setPreferredSize(new java.awt.Dimension(763, 459));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Quicksand SemiBold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Toy Mart");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 130, 40));

        jLabel2.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("M.Cashier");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 90, 40));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sales", 0, 0, new java.awt.Font("Quicksand SemiBold", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Quicksand", 1, 13)); // NOI18N
        jLabel3.setText("Amount");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Quicksand", 1, 13)); // NOI18N
        jLabel4.setText("Toy ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Quicksand", 1, 13)); // NOI18N
        jLabel5.setText("Toy Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Quicksand", 1, 13)); // NOI18N
        jLabel6.setText("Qty");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Quicksand", 1, 13)); // NOI18N
        jLabel7.setText("Price");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        toyamount.setFont(new java.awt.Font("Quicksand", 3, 13)); // NOI18N
        toyamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toyamountActionPerformed(evt);
            }
        });
        jPanel2.add(toyamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 70, -1));

        toyid.setFont(new java.awt.Font("Quicksand", 3, 13)); // NOI18N
        toyid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                toyidKeyPressed(evt);
            }
        });
        jPanel2.add(toyid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, -1));

        toyprice.setFont(new java.awt.Font("Quicksand", 3, 13)); // NOI18N
        jPanel2.add(toyprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 80, -1));

        toyqty.setFont(new java.awt.Font("Quicksand", 3, 13)); // NOI18N
        toyqty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                toyqtyStateChanged(evt);
            }
        });
        jPanel2.add(toyqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 50, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Quicksand SemiBold", 1, 13)); // NOI18N
        jButton1.setText("Add Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 100, 30));

        toyname.setFont(new java.awt.Font("Quicksand", 3, 13)); // NOI18N
        jPanel2.add(toyname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 110, -1));

        jButton4.setBackground(new java.awt.Color(204, 153, 0));
        jButton4.setFont(new java.awt.Font("Quicksand SemiBold", 1, 14)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 440, 130));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Quicksand SemiBold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 153));
        jLabel8.setText("Total");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Quicksand SemiBold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 153));
        jLabel9.setText("Balance");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Quicksand SemiBold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 153));
        jLabel10.setText("Payment");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        toybalance.setFont(new java.awt.Font("Quicksand", 3, 13)); // NOI18N
        jPanel3.add(toybalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 260, -1));

        finaltotal.setFont(new java.awt.Font("Quicksand", 3, 13)); // NOI18N
        jPanel3.add(finaltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 260, -1));

        toypayment.setFont(new java.awt.Font("Quicksand", 3, 13)); // NOI18N
        jPanel3.add(toypayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, -1));

        bill.setColumns(20);
        bill.setRows(5);
        jScrollPane2.setViewportView(bill);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 260, 150));

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setFont(new java.awt.Font("Quicksand SemiBold", 1, 14)); // NOI18N
        jButton3.setText("Print Bill");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 130, -1));

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("Quicksand SemiBold", 1, 14)); // NOI18N
        jButton2.setText("Generate Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 120, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 280, 360));

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setFont(new java.awt.Font("Quicksand SemiBold", 1, 13)); // NOI18N
        jTable1.setForeground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Toy ID", "Toy Name", "Qty", "Price", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 440, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toyamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toyamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toyamountActionPerformed

    public void Balance() {
        double total = Double.parseDouble(finaltotal.getText());
        double pay = Double.parseDouble(toypayment.getText());

        double bal = pay - total;

        toybalance.setText(String.valueOf(bal));

    }

    public void Bill() {
        String total = finaltotal.getText();
        String pay = toypayment.getText();
        String bal = toybalance.getText();

        DefaultTableModel model = new DefaultTableModel();

        model = (DefaultTableModel) jTable1.getModel();

        bill.setText(bill.getText() + "*****************************************************\n");
        bill.setText(bill.getText() + "*     Generated Bill - Toy Mart    *\n");
        bill.setText(bill.getText() + "******************************************************\n");

        //head
        bill.setText(bill.getText() + "Product" + "\t" + "Price" + "\t" + "Amount" + "\n");

        for (int i = 0; i < model.getRowCount(); i++) {
            String pname = (String) model.getValueAt(i, 1);
            String price = (String) model.getValueAt(i, 2);
            String amount = (String) model.getValueAt(i, 3);

            bill.setText(bill.getText() + pname + "\t" + price + "\t" + amount + "\n");

        }

        bill.setText(bill.getText() + "\n");
        bill.setText(bill.getText() + "\n");

        bill.setText(bill.getText() + "\t" + "\t" + "Subtotal :" + total + "\n");
        bill.setText(bill.getText() + "\t" + "\t" + "Pay :" + total + "\n");
        bill.setText(bill.getText() + "\t" + "\t" + "Balance :" + total + "\n");

        bill.setText(bill.getText() + "\n");
        bill.setText(bill.getText() + "**********************************************************\n");

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) jTable1.getModel();

        model.addRow(new Object[]{
            toyid.getText(),
            toyname.getText(),
            toyqty.getValue().toString(),
            toyprice.getText(),
            toyamount.getText(),});

        double sum = 0;

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 4).toString());

        }

        finaltotal.setText(Double.toString(sum));

        toyid.setText("");
        toyname.setText("");
        toyprice.setText("");
        toyamount.setText("");

        toyid.requestFocus();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void toyidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toyidKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String tid = toyid.getText();

            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/lankesh", "root", "Wikum@123");
                pst = con.prepareStatement("SELECT * FROM toys WHERE id = ?");
                pst.setString(1, tid);
                rs = pst.executeQuery();

                if (rs.next() == false) {
                    JOptionPane.showMessageDialog(this, "Entered Product Code Not Available");
                } else {
                    String tname = rs.getString("productname");
                    String tprice = rs.getString("price");

                    toyname.setText(tname.trim());
                    toyprice.setText(tprice.trim());
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Cashier_func_manager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Cashier_func_manager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_toyidKeyPressed

    private void toyqtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_toyqtyStateChanged

        double qty = Double.parseDouble(toyqty.getValue().toString());
        double price = Double.parseDouble(toyprice.getText());

        double tot = qty * price;

        toyamount.setText(String.valueOf(tot));

    }//GEN-LAST:event_toyqtyStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Balance();
        Bill();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            bill.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Cashier_func_manager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Login im = new Login();
        im.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier_func_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier_func_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier_func_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier_func_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashier_func_manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bill;
    private javax.swing.JTextField finaltotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField toyamount;
    private javax.swing.JTextField toybalance;
    private javax.swing.JTextField toyid;
    private javax.swing.JTextField toyname;
    private javax.swing.JTextField toypayment;
    private javax.swing.JTextField toyprice;
    private javax.swing.JSpinner toyqty;
    // End of variables declaration//GEN-END:variables
}
