/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Logins;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     *
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        exitbtn = new javax.swing.JButton();
        logbtn = new javax.swing.JButton();
        resetbtn1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        usertype = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toy Mart Login Panel");

        login_panel.setBackground(new java.awt.Color(51, 51, 51));
        login_panel.setForeground(new java.awt.Color(51, 51, 51));
        login_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Quicksand SemiBold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Toy Mart");
        login_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 130, 40));

        jLabel2.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("System Login");
        login_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 90, 40));

        jLabel3.setFont(new java.awt.Font("Quicksand SemiBold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("User Type : ");
        login_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, 40));

        jLabel4.setFont(new java.awt.Font("Quicksand SemiBold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Username : ");
        login_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 110, 40));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        login_panel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 200, -1));
        login_panel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 200, -1));

        exitbtn.setBackground(new java.awt.Color(102, 204, 255));
        exitbtn.setFont(new java.awt.Font("Quicksand SemiBold", 1, 13)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(0, 0, 0));
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        login_panel.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 100, -1));

        logbtn.setBackground(new java.awt.Color(255, 204, 204));
        logbtn.setFont(new java.awt.Font("Quicksand SemiBold", 1, 13)); // NOI18N
        logbtn.setForeground(new java.awt.Color(0, 0, 0));
        logbtn.setText("Login");
        logbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbtnActionPerformed(evt);
            }
        });
        login_panel.add(logbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 100, -1));

        resetbtn1.setBackground(new java.awt.Color(153, 255, 153));
        resetbtn1.setFont(new java.awt.Font("Quicksand SemiBold", 1, 13)); // NOI18N
        resetbtn1.setForeground(new java.awt.Color(0, 0, 0));
        resetbtn1.setText("Reset");
        resetbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtn1ActionPerformed(evt);
            }
        });
        login_panel.add(resetbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 100, -1));

        jLabel5.setFont(new java.awt.Font("Quicksand SemiBold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Password : ");
        login_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, 40));

        usertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cashier", "Manager", " " }));
        login_panel.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void logbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbtnActionPerformed

        try {
            String query = "SELECT * FROM `systemlog` WHERE username=? AND password=? AND usertype=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/lankesh", "root", "");
            pst = con.prepareStatement(query);
            pst.setString(1, username.getText());
            pst.setString(2, password.getText());
            pst.setString(3, String.valueOf(usertype.getSelectedItem()));
            rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Username and Password matched and you are logined as " + rs.getString("usertype"));
                if (usertype.getSelectedIndex() == 0) {

                    Itemmanage c1 = new Itemmanage();
                    c1.setVisible(true);
                    this.setVisible(false);
                } else {
                    Login_manager m1 = new Login_manager();
                    m1.setVisible(true);
                    this.setVisible(false);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Username and Password does not matched");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_logbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void resetbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtn1ActionPerformed
        password.setText(null);
        username.setText(null);
    }//GEN-LAST:event_resetbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton logbtn;
    private javax.swing.JPanel login_panel;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton resetbtn1;
    private javax.swing.JTextField username;
    private javax.swing.JComboBox<String> usertype;
    // End of variables declaration//GEN-END:variables

}
